/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_buggysofts_jniexp_TwoArgs.h"

JNIEXPORT jint JNICALL Java_com_buggysofts_jniexp_TwoArgs_getResult(JNIEnv *, jobject, jint a, jint b){
    return a+b;
}
