/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buggysofts_jniexp_ObjArgs */

#ifndef _Included_com_buggysofts_jniexp_ObjArgs
#define _Included_com_buggysofts_jniexp_ObjArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buggysofts_jniexp_ObjArgs
 * Method:    createObj
 * Signature: (Ljava/lang/String;D)Lcom/buggysofts/jniexp/NativePassableObject;
 */
JNIEXPORT jobject JNICALL Java_com_buggysofts_jniexp_ObjArgs_createObj
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_buggysofts_jniexp_ObjArgs
 * Method:    getObjStr
 * Signature: (Lcom/buggysofts/jniexp/NativePassableObject;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_buggysofts_jniexp_ObjArgs_getObjStr
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
