/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buggysofts_jniexp_TwoArgs */

#ifndef _Included_com_buggysofts_jniexp_TwoArgs
#define _Included_com_buggysofts_jniexp_TwoArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buggysofts_jniexp_TwoArgs
 * Method:    getResult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_buggysofts_jniexp_TwoArgs_getResult(JNIEnv *, jobject, jint a, jint b);

#ifdef __cplusplus
}
#endif
#endif
