/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buggysofts_jniexp_NoArgs */

#ifndef _Included_com_buggysofts_jniexp_NoArgs
#define _Included_com_buggysofts_jniexp_NoArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buggysofts_jniexp_NoArgs
 * Method:    getResult
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buggysofts_jniexp_NoArgs_getResult
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
